### ISSUE TITLE
Feature request: change child without restarting windup

### ISSUE THREAD

**Issue by calummackervoy** [sgwilym/windups#32]
From the guides:

> Let me be clear: changing the value of a windup while it's running will restart it from scratch. At least... that's how it's meant to work.

I'd really like to change the styles of the text mid-windup (exactly as with [the example in the guide](https://windups.gwil.co/guides#restarting)), re-rendering the colour of the text but _without_ restarting the windup. The specific animation is to type out some text, and then when it's finished it becomes bold and red (mimicking a phone PIN attempt fail)

I suppose that it would be best served as a prop into `WindupChildren`? It isn't clear to me immediately looking at the code, do you have any pointers into how I might implement it this? A priori the prop could cause the old position/index of the windup animation to be saved, and it would restart from here? Is this feature desirable? If I can do it I think it would be one of the little details which would make my animation better 🙂

**Comment by calummackervoy** [comment]
I managed to get the behaviour I wanted by moving the CSS logic outside of the `WindupChildren`

```
function PinAttempt({pace, midPause}: {pace: number, midPause: number}) : React.ReactElement {
    const [pinFin, setPinFin] = useState(false);

    return (
        <Container textWeight={pinFin ? "bold" : null} color={pinFin ? "red" : null}>
            <Center>
                <WindupChildren>
                    <Pace ms={pace}><Text>* * <Pause ms={midPause}/>* *</Text></Pace>
                    <Effect fn={() => setPinFin(true)} />
                </WindupChildren>
            </Center>
        </Container>
    );
}
```

It's great use for my use case but it's not ideal I think if it's part of a larger Windup sequence ... you'd need to move the text into its' own component, and use a `Pause` component to make sure that the main animation doesn't race ahead

**Comment by sgwilym** [comment]
Sorry for the late reply. I think you solved this the 'right' way! You could also use `WindupChildren`'s `onFinished` prop rather than `<Effect>`.

Would you be so kind as to explain the issue with a larger windup sequence you started to describe?

**Comment by calummackervoy** [comment]
I'm not sure I remember what I meant by "larger sequences" actually 😅 in trying to find what I had been thinking about I re-wrote a better explanation of my problem/solution which might be useful:

So essentially I was trying to change the colour of the text "****" to red at the end of the animation to show that the "pin attempt" made by the character failed. So I wanted to change the colour of the text, like in the guide, but _without_ re-running the animation

To achieve this I made the above `PinAttempt` component, and then nested that within my animation component, like so:

```
...
return (
    ...
    <Pause ms={SHORT_PAUSE} />
    <PinAttempt pace={SLOW_PACE} midPause={0} />
    <Pause ms={SHORT_PAUSE} />
    <PinAttempt pace={SLOW_PACE*0.5} midPause={SHORT_PAUSE*0.5} />
    ...
);
```

When the pinFin state is changed on the `PinAttempt` component React re-renders it, but since the shape of the children hasn't changed Windups doesn't restart the animation
