### ISSUE TITLE
Is there a way to add cursor?

### ISSUE THREAD

**Issue by yinkakun** [sgwilym/windups#35]
Great Job, this is the only library I've seen that allows animating react components and not just plain strings. But I'm using it on a terminal-like component, so I'm wondering if there's a way to add a cursor. 

Thanks so much for your efforts.

**Comment by sgwilym** [comment]
Hi @yinkakun, thanks for the kind words.

How about adding a cursor like this?

```
<>
  <WindupChildren>
    This looks like I'm typing it!
  </WindupChildren>
  <img src="blinking-cursor.gif" />
</>
```

That `img` could be a component rendering your cursor however you want, of course. Just make sure that it uses `display: inline` in its css so that it renders on the same line as your text.
