### ISSUE TITLE
Slow <WindupChildren> down

### ISSUE THREAD

**Issue by Quark03** [sgwilym/windups#36]
Hi, first of all. I love the package. It's soooo awesome. 
Secondly, I would like to know if there is some way of giving the hole <WindipChildren> component like a default pace. The overall animation is too fast for my use case. And the possibility of allowing different paces would be a great addition to my project

**Comment by Quark03** [comment]
Ok, I figured a way. Not sure if it's the best. I am surrounding all the WindupChildren children with a Pace component and giving it a slower ms

**Comment by sgwilym** [comment]
@Quark03 That's pretty much the way to do it!
