### ISSUE TITLE
React component with windups not working in Astro.

### ISSUE THREAD

**Issue by dreyfus92** [sgwilym/windups#61]
I'm trying to use windups with Astro in a component made with React but, I get this error from Astro. 

<img width="1273" alt="image" src="https://user-images.githubusercontent.com/85648028/214715143-52ddc87d-719d-4e68-ba33-f975f9285ac4.png">

Any ideas?

**Comment by sgwilym** [comment]
No idea. It _looks_ like the import is not working, as the windups module is coming back `undefined`. Were you able to solve tihs?

**Comment by dreyfus92** [comment]
I ended up using a different package to achieve my goal, wasn't able to figure out what was breaking my code.
