### ISSUE TITLE
type declaration file is not working

### ISSUE THREAD

**Issue by flingyp** [sgwilym/windups#65]
windups type declaration file is not working

**Comment by flingyp** [comment]
#66 Thank you for writing this library, I am using it but I find that its declaration file is not working

**Comment by sgwilym** [comment]
Thanks for the report flingyp. Can you tell me what kind of errors you're getting? No changes have been made to this module for a long time, and for the type declaration file to stop working suddenly is strange!

**Comment by flingyp** [comment]
![image](https://github.com/sgwilym/windups/assets/57666140/9fd110ad-73d9-4204-bd0a-3e572836c9d7)

![image](https://github.com/sgwilym/windups/assets/57666140/38069f69-9847-4974-9cbe-8bd780adb758)

Could not find a declaration file for module 'windups'. 'F:/Personal Projects/me/node_modules/.pnpm/windups@1.2.1_react@18.2.0/node_modules/windups/dist/windups.esm.js' implicitly has an 'any' type.
  There are types at 'f:/Personal Projects/me/node_modules/windups/dist/index.d.ts', but this result could not be resolved when respecting package.json "exports". The 'windups' library may need to update its package.json or typings.

Ts error message as above. This is a Nest.js project and typescript version is v5.2.2. 

I don't know too why typescript not find declare file. But I added the types field to exports and it worked fine.

**Comment by sgwilym** [comment]
Fixed by #66

**Comment by sgwilym** [comment]
Published in v1.2.2
