### ISSUE TITLE
NextJS ,when I install tha windups package tell me Could not find a declaration file for module 'windups'

### ISSUE THREAD

**Issue by SaulAugustoGascaFarreraDeveloper** [sgwilym/windups#67]
when i install and update the package tell me,Could not find a declaration file for module 'windups'. 'c:/NextJSProjects/uravatar-studio-project/node_modules/windups/dist/windups.esm.js' implicitly has an 'any' type.
  There are types at 'c:/NextJSProjects/uravatar-studio-project/node_modules/windups/dist/index.d.ts', but this result could not be resolved when respecting package.json "exports". The 'windups' library may need to update its package.json or typings.ts(7016)

**Comment by sgwilym** [comment]
The fix for this issue should be available in v1.2.2.
