### ISSUE TITLE
Feature request: Possibility to start with an initial string

### ISSUE THREAD

**Issue by marcuslindfeldt** [sgwilym/windups#7]
It would be great if you could start with an initial string and "windup" by replacing characters instead of starting with an empty string.

E.g. Replacing the English word "Christmas" to Spanish "Navidad"

Initial render:
Christmas
First character replacement:
`N`hristmas
Second character replacement:
`Na`ristmas
Etc...
`Nav`istmas
`Navi`stmas
`Navid`tmas

It would also be cool if you could animate the "rest" of the characters that haven't been replaced yet e.g. by lowering the opacity or something. My specific use case is for animating a translation like above.

**Comment by sgwilym** [comment]
@marcuslindfeldt  Hey! This is a fun animation idea.

I don't think it'll be built into windups, as it would require a pretty serious refactor of the underlying `Cassette` data structure windups uses to model its progress.

The good news is I think it would be quite straightforward to make a custom hook that does this:

```js
useOverlaidWindup(startString, endString) {
  // Use the end string as a windup
  const [windup, { isFinished }] = useWindup(endString);
  
  // Slice off as much from the start of the end string as the length of the windup
  const clipped = endString.slice(windup.length);
  
  // If the windup is finished, show the endstring no matter what
  return isFinished ? windup : `${windup}${clipped}`
}

// Use it!
useOverlaidWindup("Christmas", "Navidad")
```
